export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const LOGOUT = 'LOGOUT'

export const ROUTE_CHANGE = 'ROUTE_CHANGE'

export const GET_PAGE = 'GET_PAGE'
export const GET_PAGE_BY_TITLE = 'GET_PAGE_BY_TITLE'
export const GET_ACTIVE_PAGE_HISTORY = 'GET_ACTIVE_PAGE_HISTORY'
export const GET_MORE_ACTIVE_PAGE_HISTORY = 'GET_MORE_ACTIVE_PAGE_HISTORY'
export const UPDATE_PAGE = 'UPDATE_PAGE'
export const CREATE_PAGE = 'CREATE_PAGE'
export const SET_ACTIVE_PAGE = 'SET_ACTIVE_PAGE'
export const START_PAGE_EDITING = 'START_PAGE_EDITING'
export const STOP_PAGE_EDITING = 'STOP_PAGE_EDITING'
export const UPDATE_EDITED_TITLE = 'UPDATE_EDITED_TITLE'
export const UPDATE_EDITED_TEXT = 'UPDATE_EDITED_TEXT'
export const requestStates = {
  SUCCESS: 'success',
  FAIL: 'fail',
  START: 'start'
}
